# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormSignIn.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from FormSignUp import *
from landingPage2 import *
import pymysql
import pymysql.cursors
import test_rc


class Ui_FormSignIn(object):
    def koneksi(self):
        con = pymysql.connect(db='prono', user='root', password='', host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        if(cur):
            self.messagebox("Koneksi", "Koneksi Berhasil")
        else:
            self.messagebox("Koneksi", "Koneksi Gagal")

    def messagebox(self, title, message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()

    def setupUi(self, FormSignIn):
        FormSignIn.setObjectName("FormSignIn")
        FormSignIn.resize(850, 500)
        FormSignIn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gambarLogin = QtWidgets.QLabel(FormSignIn)
        self.gambarLogin.setGeometry(QtCore.QRect(50, 130, 321, 301))
        self.gambarLogin.setStyleSheet("background-image: url(:/newPrefix/undraw_Progress_tracking_re_ulfg.png);")
        self.gambarLogin.setText("")
        self.gambarLogin.setPixmap(QtGui.QPixmap(":/newPrefix/undraw_Progress_tracking_re_ulfg.png"))
        self.gambarLogin.setScaledContents(True)
        self.gambarLogin.setObjectName("gambarLogin")
        self.labelUsername = QtWidgets.QLabel(FormSignIn)
        self.labelUsername.setGeometry(QtCore.QRect(418, 200, 105, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelUsername.setFont(font)
        self.labelUsername.setStyleSheet("color: rgb(20, 122, 214);")
        self.labelUsername.setObjectName("labelUsername")
        self.label_Pass = QtWidgets.QLabel(FormSignIn)
        self.label_Pass.setGeometry(QtCore.QRect(420, 240, 100, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_Pass.setFont(font)
        self.label_Pass.setStyleSheet("color: rgb(20, 122, 214);")
        self.label_Pass.setObjectName("label_Pass")
        self.lineEdit_Username = QtWidgets.QLineEdit(FormSignIn)
        self.lineEdit_Username.setGeometry(QtCore.QRect(530, 200, 261, 20))
        self.lineEdit_Username.setObjectName("lineEdit_Username")
        self.lineEdit_Password = QtWidgets.QLineEdit(FormSignIn)
        self.lineEdit_Password.setGeometry(QtCore.QRect(530, 240, 261, 20))
        self.lineEdit_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.pushButton_SignUp1 = QtWidgets.QPushButton(FormSignIn)
        self.pushButton_SignUp1.setGeometry(QtCore.QRect(540, 310, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_SignUp1.setFont(font)
        self.pushButton_SignUp1.setStyleSheet("color: rgb(20, 122, 214);\n"
"border: 2px solid;\n"
"border-color: rgb(20, 122, 214);\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton_SignUp1.setDefault(False)
        self.pushButton_SignUp1.setFlat(False)
        self.pushButton_SignUp1.setObjectName("pushButton_SignUp1")
        self.pushButton_SignIn = QtWidgets.QPushButton(FormSignIn)
        self.pushButton_SignIn.setGeometry(QtCore.QRect(680, 310, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_SignIn.setFont(font)
        self.pushButton_SignIn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(20, 122, 214);")
        self.pushButton_SignIn.setAutoDefault(False)
        self.pushButton_SignIn.setDefault(True)
        self.pushButton_SignIn.setFlat(False)
        self.pushButton_SignIn.setObjectName("pushButton_SignIn")
        self.label_Welcome = QtWidgets.QLabel(FormSignIn)
        self.label_Welcome.setGeometry(QtCore.QRect(50, 20, 250, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_Welcome.setFont(font)
        self.label_Welcome.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_Welcome.setStyleSheet("color: rgb(20, 122, 214);")
        self.label_Welcome.setObjectName("label_Welcome")
        self.label_ToProNo = QtWidgets.QLabel(FormSignIn)
        self.label_ToProNo.setGeometry(QtCore.QRect(200, 70, 250, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_ToProNo.setFont(font)
        self.label_ToProNo.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_ToProNo.setStyleSheet("color: rgb(20, 122, 214);")
        self.label_ToProNo.setObjectName("label_ToProNo")
        self.labelSignToCont = QtWidgets.QLabel(FormSignIn)
        self.labelSignToCont.setGeometry(QtCore.QRect(440, 130, 351, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelSignToCont.setFont(font)
        self.labelSignToCont.setStyleSheet("color: rgb(20, 122, 214);")
        self.labelSignToCont.setObjectName("labelSignToCont")
        self.labelPlease1 = QtWidgets.QLabel(FormSignIn)
        self.labelPlease1.setGeometry(QtCore.QRect(532, 350, 121, 21))
        self.labelPlease1.setObjectName("labelPlease1")
        self.labelPlease2 = QtWidgets.QLabel(FormSignIn)
        self.labelPlease2.setGeometry(QtCore.QRect(555, 370, 71, 16))
        self.labelPlease2.setObjectName("labelPlease2")
        self.gambarLogin.raise_()
        self.labelUsername.raise_()
        self.label_Pass.raise_()
        self.lineEdit_Username.raise_()
        self.lineEdit_Password.raise_()
        self.pushButton_SignIn.raise_()
        self.pushButton_SignUp1.raise_()
        self.label_Welcome.raise_()
        self.label_ToProNo.raise_()
        self.labelSignToCont.raise_()
        self.labelPlease1.raise_()
        self.labelPlease2.raise_()

        self.pushButton_SignUp1.clicked.connect(self.openSignUp)

        self.pushButton_SignIn.clicked.connect(self.login)

        self.retranslateUi(FormSignIn)
        QtCore.QMetaObject.connectSlotsByName(FormSignIn)

    def retranslateUi(self, FormSignIn):
        _translate = QtCore.QCoreApplication.translate
        FormSignIn.setWindowTitle(_translate("FormSignIn", "Form"))
        self.labelUsername.setText(_translate("FormSignIn", "Username"))
        self.label_Pass.setText(_translate("FormSignIn", "Password"))
        self.pushButton_SignUp1.setToolTip(_translate("FormSignIn", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_SignUp1.setText(_translate("FormSignIn", "Sign Up"))
        self.pushButton_SignIn.setToolTip(_translate("FormSignIn", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_SignIn.setText(_translate("FormSignIn", "Sign In"))
        self.label_Welcome.setText(_translate("FormSignIn", "Welcome"))
        self.label_ToProNo.setText(_translate("FormSignIn", "To ProNo"))
        self.labelSignToCont.setText(_translate("FormSignIn", "Sign In to Continue"))
        self.labelPlease1.setText(_translate("FormSignIn", "Don\'t have any account? "))
        self.labelPlease2.setText(_translate("FormSignIn", "Please Sign Up."))

    def login(self):
        username = self.lineEdit_Username.text()
        password = self.lineEdit_Password.text()
        con = pymysql.connect(db='prono', user='root', password='', host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        sql = "SELECT username, password from user where username=%s and password=%s"

        data = cur.execute(sql, (username, password))
        if (len(cur.fetchall()) > 0):
            self.messagebox("SUKSES", "Sukses Login")
            self.openLandingPage()
            # self.FormSignIn.hide()
        else:
            self.messagebox("GAGAL", "Username atau Password Salah ! ")

    def openSignUp(self):
        # self.formsignup()
        self.form = formsignup()
        self.form.show()

    def openLandingPage(self):
        # self.formsignup()
        # self.form = landingPage()
        self.form = landingPage2()
        self.form.show()

    # def closeSignIn(self):
    #     self.form = Ui_FormSignIn()
    #     self.Ui

# class landingPage(QMainWindow):
#     def __init__(self):
#         super().__init__()
#         self.landingPage = Ui_LandingPage()
#         self.landingPage.setupUi(self)
#         self.show()

class landingPage2(QMainWindow):
    def __init__(self):
        super().__init__()
        self.landingPage2 = Ui_LandingPage2()
        self.landingPage2.setupUi(self)
        self.show()

class formsignup(QWidget):
    def __init__(self):
        super().__init__()
        self.formsignup = Ui_FormSignUp()
        self.formsignup.setupUi(self)
        self.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormSignIn = QtWidgets.QWidget()
    ui = Ui_FormSignIn()
    ui.setupUi(FormSignIn)
    FormSignIn.show()
    sys.exit(app.exec_())
