# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormSignUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import pymysql
import pymysql.cursors
from FormSignIn import *
import test_rc
import tes2_rc
import chart_rc

class Ui_FormSignUp(object):
    def koneksi(self):
        con = pymysql.connect(db='prono', user='root', password='', host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        if(cur):
            self.messagebox("Koneksi", "Koneksi Berhasil")
        else:
            self.messagebox("Koneksi", "Koneksi Gagal")

    def messagebox(self, title, message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()

    # def __init__(self):
    #     super().__init__()
    #     self.hideFormSignUp = Ui_FormSignIn()

    def setupUi(self, FormSignUp):
        self.koneksi()
        # self.closeSignIn()
        FormSignUp.setObjectName("FormSignUp")
        FormSignUp.resize(425, 500)
        FormSignUp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_NoHp = QtWidgets.QLabel(FormSignUp)
        self.label_NoHp.setGeometry(QtCore.QRect(35, 300, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_NoHp.setFont(font)
        self.label_NoHp.setStyleSheet("color: rgb(20, 122, 214);")
        self.label_NoHp.setObjectName("label_NoHp")
        self.lineEdit_NoHp = QtWidgets.QLineEdit(FormSignUp)
        self.lineEdit_NoHp.setGeometry(QtCore.QRect(125, 300, 261, 20))
        self.lineEdit_NoHp.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_NoHp.setObjectName("lineEdit_NoHp")
        self.labelEmail = QtWidgets.QLabel(FormSignUp)
        self.labelEmail.setGeometry(QtCore.QRect(35, 260, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelEmail.setFont(font)
        self.labelEmail.setStyleSheet("color: rgb(20, 122, 214);")
        self.labelEmail.setObjectName("labelEmail")
        self.lineEdit_Email = QtWidgets.QLineEdit(FormSignUp)
        self.lineEdit_Email.setGeometry(QtCore.QRect(125, 260, 261, 20))
        self.lineEdit_Email.setObjectName("lineEdit_Email")
        self.label_Pass_2 = QtWidgets.QLabel(FormSignUp)
        self.label_Pass_2.setGeometry(QtCore.QRect(35, 380, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_Pass_2.setFont(font)
        self.label_Pass_2.setStyleSheet("color: rgb(20, 122, 214);")
        self.label_Pass_2.setObjectName("label_Pass_2")
        self.lineEdit_Password_2 = QtWidgets.QLineEdit(FormSignUp)
        self.lineEdit_Password_2.setGeometry(QtCore.QRect(125, 380, 261, 20))
        self.lineEdit_Password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_Password_2.setObjectName("lineEdit_Password_2")
        self.labelUsername_2 = QtWidgets.QLabel(FormSignUp)
        self.labelUsername_2.setGeometry(QtCore.QRect(35, 340, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelUsername_2.setFont(font)
        self.labelUsername_2.setStyleSheet("color: rgb(20, 122, 214);")
        self.labelUsername_2.setObjectName("labelUsername_2")
        self.lineEdit_Username_2 = QtWidgets.QLineEdit(FormSignUp)
        self.lineEdit_Username_2.setGeometry(QtCore.QRect(125, 340, 261, 20))
        self.lineEdit_Username_2.setObjectName("lineEdit_Username_2")
        self.gambarSignUp = QtWidgets.QLabel(FormSignUp)
        self.gambarSignUp.setGeometry(QtCore.QRect(93, 10, 231, 141))
        self.gambarSignUp.setStyleSheet("background-image: url(:/newPrefix/undraw_fill_in_mie5.png);")
        self.gambarSignUp.setText("")
        self.gambarSignUp.setPixmap(QtGui.QPixmap(":/newPrefix/undraw_fill_in_mie5.png"))
        self.gambarSignUp.setScaledContents(True)
        self.gambarSignUp.setObjectName("gambarSignUp")
        self.lineEdit_Nama = QtWidgets.QLineEdit(FormSignUp)
        self.lineEdit_Nama.setGeometry(QtCore.QRect(125, 220, 261, 20))
        self.lineEdit_Nama.setObjectName("lineEdit_Nama")
        self.labelNama = QtWidgets.QLabel(FormSignUp)
        self.labelNama.setGeometry(QtCore.QRect(35, 220, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelNama.setFont(font)
        self.labelNama.setStyleSheet("color: rgb(20, 122, 214);")
        self.labelNama.setObjectName("labelNama")
        self.pushButton_SignUp2 = QtWidgets.QPushButton(FormSignUp)
        self.pushButton_SignUp2.setGeometry(QtCore.QRect(160, 420, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_SignUp2.setFont(font)
        self.pushButton_SignUp2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(20, 122, 214);\n"
"")
        self.pushButton_SignUp2.setDefault(True)
        self.pushButton_SignUp2.setFlat(False)
        self.pushButton_SignUp2.setObjectName("pushButton_SignUp2")
        self.labelSignToCont = QtWidgets.QLabel(FormSignUp)
        self.labelSignToCont.setGeometry(QtCore.QRect(35, 180, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelSignToCont.setFont(font)
        self.labelSignToCont.setStyleSheet("color: rgb(20, 122, 214);")
        self.labelSignToCont.setObjectName("labelSignToCont")

        self.retranslateUi(FormSignUp)
        QtCore.QMetaObject.connectSlotsByName(FormSignUp)

    def retranslateUi(self, FormSignUp):
        _translate = QtCore.QCoreApplication.translate
        FormSignUp.setWindowTitle(_translate("FormSignUp", "Form"))
        self.label_NoHp.setText(_translate("FormSignUp", "No. Hp"))
        self.labelEmail.setText(_translate("FormSignUp", "Email"))
        self.label_Pass_2.setText(_translate("FormSignUp", "Password"))
        self.labelUsername_2.setText(_translate("FormSignUp", "Username"))
        self.labelNama.setText(_translate("FormSignUp", "Nama"))
        self.pushButton_SignUp2.setToolTip(_translate("FormSignUp", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton_SignUp2.setText(_translate("FormSignUp", "Sign Up"))
        self.labelSignToCont.setText(_translate("FormSignUp", "Enter your personal data here..."))

        self.pushButton_SignUp2.clicked.connect(self.submit)

    def submit(self):
        nama_user = self.lineEdit_Nama.text()
        username = self.lineEdit_Username_2.text()
        email = self.lineEdit_Email.text()
        no_telp = self.lineEdit_NoHp.text()
        password = self.lineEdit_Password_2.text()

        insert = (nama_user, username, email, no_telp, password)

        print(insert)
        if self.lineEdit_Nama.text() and self.lineEdit_Username_2.text()\
                and self.lineEdit_Email.text() and self.lineEdit_NoHp.text()\
                and self.lineEdit_Password_2.text():
            con = pymysql.connect(db='prono', user='root', password='', host='localhost', port=3306, autocommit=True)
            cur = con.cursor()
            sql = "INSERT INTO user(nama_user, username, email, no_telp, password)" + "VALUES" + str(insert)
            data = cur.execute(sql)

            self.messagebox("SUKSES", "Data Berhasil di Submit")
            self.openSignIn()

            if(len(cur.fetchall())>0):
                ui.messagebox("SUKSES", "Data Berhasil di Submit")
                # self.openSignIn()
        else:
            ui.messagebox("GAGAL", "Mohon lengkapi form ")
        # self.closeSignUp()

    def openSignIn(self):
        self.form = formsignin()
        self.form.show()

    # def closeSignIn(self):
    #     self.form = closeformsignin
    #     self.form.destroy()

class formsignin(QWidget):
    def __init__(self):
        super().__init__()
        self.formsignin = Ui_FormSignIn()
        self.formsignin.setupUi(self)
        self.show()

# class closeformsignin(QWidget):
#     def __init__(self):
#         super().__init__()
#         self.closeformsignin = Ui_FormSignIn()
#         self.closeformsignin.setupUi(self)
#         self.destroy()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormSignUp = QtWidgets.QWidget()
    ui = Ui_FormSignUp()
    ui.setupUi(FormSignUp)
    FormSignUp.show()
    sys.exit(app.exec_())
